name: am_i_drank
description: pet-project to get the drunkness level

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  http: ^1.1.0
  image: ^4.3.0
  img: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
