name: am_i_drank
description: fun pet-project to get your drunkness level
version: 0.1.0

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  http: ^1.1.0
  image: ^4.3.0
  audioplayers: ^6.1.0
  shared_preferences: ^2.3.3
  flame: ^1.22.0
  google_fonts: ^6.2.1
  nes_ui: ^0.20.0
  provider: ^6.1.2
  logging: ^1.3.0
  go_router: ^14.6.2
  flame_audio: ^2.10.6
  intl: ^0.20.1
  google_ml_kit: ^0.19.0
  blur: ^4.0.0
  floating_bubbles: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/app_icon.png
    - assets/images/
    - assets/images/bottle.png
    - assets/beer_runner/
    - assets/beer_runner/fonts/
    - assets/beer_runner/icons/
    - assets/beer_runner/images/
    - assets/beer_runner/music/
    - assets/beer_runner/sfx/
    - assets/beer_runner/images/banner.png
    - assets/beer_runner/images/ember.png
    - assets/beer_runner/images/scenery/
    - assets/beer_runner/images/scenery/background.png
    - assets/beer_runner/images/scenery/bar.png
    - assets/beer_runner/images/scenery/bar-table.png
    - assets/beer_runner/images/scenery/chairs.png
    - assets/beer_runner/images/scenery/lamps.png
    - assets/beer_runner/images/enemies/
    - assets/beer_runner/images/enemies/flying_enemy.png
    - assets/beer_runner/images/enemies/obstacles.png
    - assets/beer_runner/images/dash/
    - assets/beer_runner/images/dash/dash_still.png
    - assets/beer_runner/images/dash/dash_spritesheet.png
    - assets/beer_runner/images/dash/dash_running.png
    - assets/beer_runner/images/dash/dash_jumping.png
    - assets/beer_runner/images/dash/dash_falling.png

  fonts:
    - family: Press Start 2P
      fonts:
        - asset: assets/beer_runner/fonts/Press_Start_2P/PressStart2P-Regular.ttf
